### ISSUE TITLE
Hardcoded patchcore 1.15.0 dependency?

### ISSUE THREAD

**Issue by arj03** [Happy0/ssb-embedded-chat#1]
Probably should be ^?

**Comment by Happy0** [comment]
Hmm... I've been paranoid about using anything other than fixed versions for dependencies ever since being stung bad on one of my haskell projects that I can no longer build where I was lax about the versions. But perhaps my paranoia is unwarranted since I notice a lot of the patch-* apps use ^.

Does patchcore use semantic versioning? E.g. if they made a breaking change would they bump the first column?

I'll put my faith in your if you want to make a pull request using ^ :P.

**Comment by arj03** [comment]
It does. But package-lock.json is what fixes versions are for. For good or bad... ;-)

**Comment by arj03** [comment]
This is now causing a ton of errors in console inside patchbay :(

TypeError: Cannot read property 'shs' of undefined
    at module.exports (/home/chrx/dev/patchbay-workie/node_modules/ssb-client/index.js:51)
    at /home/chrx/dev/patchbay-workie/node_modules/ssb-embedded-chat/node_modules/patchcore/sbot.js:74
    at tryConnect (/home/chrx/dev/patchbay-workie/node_modules/pull-reconnect/index.js:14)

I can haz fix now? :dog2: :cat2:

**Comment by Happy0** [comment]
Try now? I bumped the version, and added the wee ^ .

I guess I have some reading to do about how the dependency system works... It's worrying that the version of a library a library is using can bring the whole project down :P.

**Comment by arj03** [comment]
It works :hugs:
